Enable MQTT over websockets support
Open-IoT-Service-Platform/oisp-sdk-js pull request #43
Opened 2022-05-06 15:18 UTC by oguzcankirmemis

- MQTT config now accepts an additional "protocol" property to specify
  which protocol should be used to connect.
- If "protocol" is not specified, it fallbacks to usual protocol "mqtt"
  or "mqtts", depending on whether the "secure" property is set.

resolves #41

Signed-off-by: Oguzcan Kirmemis <oguzcan.kirmemis@gmail.com>

2022-05-06 21:28 UTC, srware requested changes
I think I would prefer to add a config option called 'websockets' to make this more robust. If 'websockets' is false or doesn't exist just use mqtt or mqtts as before. The protocol config property opens up a lot of potential for failure or worse.

2022-05-06 21:28 UTC, srware commented on api/mqtt/connector.js
>                  }
I think we should do some sanity checking here to make sure protocol isn't something stupid. I assume there should be 3 valid options, mqtt, mqtts and ws?

2022-05-06 21:29 UTC, srware commented on api/mqtt/connector.js
>                  }
You can ignore this if you agree with my comments above :)

2022-05-07 17:16 UTC, oguzcankirmemis commented
Technically speaking, mqtt allows other protocols than websockets, and that was on my mind. Nevertheless, emqx does not support those and we also do not have plans to support them. So, I agree that it makes things unnecessarily complex and have changed it to use "websockets".

2022-05-09 09:39 UTC, srware approved these changes

2022-05-09 09:40 UTC, merged